pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot[bot]
      - check-success=test
      - 'title~=^build\(deps-dev\): '
    actions:
      merge:
        method: squash
